dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
dotenv: .env
networks:
  default: development
  development:
    verify: False
  ganache-local:
    verify: False
  kovan:
    verify: True
  mainnet-fork:
    verify: False
  mumbai_moralis:
    verify: True
  polygon-test:
    verify: True

wallets:
  from_key: ${PRIVATE_KEY}
